const menu = {
  headers: [
    '<h1 class="text-center">Soups/Corbalar</h1>',
    '<h1 class="text-center">Salads/Salatalar</h1>',
    '<h1 class="text-center">Cold Appetizers/Soguk Mezeler</h1>',
    '<h1 class="text-center">Hot Appetizers/Sicak Mezeler</h1>',
    '<h1 class="text-center">Wraps/Durum</h1>',
    '<h1 class="text-center">Pastas</h1>',
    '<h1 class="text-center">Vegetarian Dishes</h1>',
    '<h1 class="text-center">Pastas</h1>',
    '<h1 class="text-center">Vegetarian Dishes</h1>',
    '<h1 class="text-center">Chicken Dishes</h1>',
    '<h1 class="text-center">Seafood/Deniz Urunleri</h1>',
    '<h1 class="text-center">Meat &amp; Lamb</h1>',
    '<h1 class="text-center">Desserts</h1>'
  ],
  mealList: [
    "<h2>LENTIL Soup/Mercimek Corbasi<span>",
    "<h2>CHICKEN VEGETABLE/Sebzeli Tavuk Corbasi<span>",
    "<h2>Shepherd's salad/Coban salatasi<span>",
    "<h2>Goat Cheese Salad/Keci Peynirli Salata<span>",
    "<h2>Mediterranean Season Salad/Mevsim Akdeniz Salatasi<span>",
    "<h2>Arugula Salad/Roka Salatasi<span>",
    "<h2>Eggplant with Tomato Sauce/Domates Soslu Patlican<span>",
    "<h2>Babaganush<span>",
    "<h2>Hummus<span>",
    "<h2>Spicy Hand Chopped Vegetables/Ezme<span>",
    "<h2>Lebni/Haydari<span>",
    "<h2>Smoked Eggplant Salad/Patlican Salatasi<span>",
    "<h2>Stuffed Grape Leaves<span>",
    "<h2>Mixed Meze Plate<span>",
    "<h2>Green Beans in Olive Oil/Zeytinyagli Taze Fasulye<span>",
    "<h2>Fried Calf's Liver/Arnavut Cigeri <span>",
    "<h2>Cigar Rolls/Sigara Boregi<span>",
    "<h2>Fried Calamari/Calamar Tava<span>",
    "<h2>Stuffed Bulgur Balls/Icli Kofte<span>",
    "<h2>Zucchini Pancake/Mucver<span>",
    "<h2>Grilled Calamari/Kalamar Izgara<span>",
    "<h2>Falafel (5 pieces)<span>",
    "<h2>Mix hot appetizers<span>",
    "<h2>Chicken Fingers<span>",
    "<h2>Spinach &amp; Cheese Borek<span>",
    "<h2>Meat Muska Borek <span>",
    "<h2>French Fries/Potatos Tava<span>",
    "<h2>Steamed Mussels/Buharda Pisirilmis Midye<span>",
    "<h2>Galata Special Wrap/Galata Durum <span>",
    "<h2>Doner Wrap/Doner Durum<span>",
    "<h2>Adana Wrap/Adana Durum<span>",
    "<h2>Chicken Adana Wrap/Tavuk Adana Durum<span>",
    "<h2>Grilled Chicken Wrap/Tavuk Durum<span>",
    "<h2>Falafel Wrap<span>",
    "<h2>All wraps served with french fries<span>",
    "<h2>Seafood Linguine/Deniz Mahsulleri Linguini<span>",
    "<h2>Homemade Turkish Dumpling/Manti<span>",
    "<h2>Penne Alla Vodka/Vodka Soslu Penne<span>",
    "<h2>Baby Okra/Bamya<span>",
    "<h2>Mixed Vegetable/Turlu<span>",
    "<h2>Falafel Dinner<span>",
    "<h2>Seasonal Vegetable Sautee/Sebze Sote<span>",
    "<h2>Chicken Curry/Kori Soslu Tavuk<span>",
    "<h2>Chicken Shish/Tavuk Sis<span>",
    "<h2>Chicken Saute/Tavuk Sote<span>",
    "<h2>Chicken Adana/Tavuk Adana<span>",
    "<h2>Chicken Pacatta<span>",
    "<h2>Grilled Chicken Wings/Izgara Tavuk Kanatlari<span>",
    "<h2>Chicken Cheese Kofte/Kasarli Tavuk Kofte<span>",
    "<h2>Chicken Sultan’s Delight<span>",
    "<h2>Chicken Chops/Tavuk Pirzola<span>",
    "<h2>Salmon Scaloppini<span>",
    "<h2>Shrimp Casserole/Karides Guvec<span>",
    "<h2>Grilled Bronzini/Levrek<span>",
    "<h2>Grilled Shrimp/Izgara Karides<span>",
    "<h2>Grilled Salmon/Izgara Somon<span>",
    "<h2>Seafood Guvec/Deniz Mahsulleri Guvec<span>",
    "<h2>Grilled or Pan Fried Trout Butterfly /Alabalik<span>",
    "<h2>Lamb Shank/Kuzu Bacagi<span>",
    "<h2>Baby Lamb Chops/Kuzu Pirzola<span>",
    "<h2>Sultan's Delight/Hunkar Begendi<span>",
    "<h2>Stuffed Cabbage/Lahana Dolmasi<span>",
    "<h2>Adana Kebab<span>",
    "<h2>Lamb Shish/Kuzu Sis<span>",
    "<h2>Grilled Meatballs/Kasap Kofte<span>",
    "<h2>Iskender Kebab<span>",
    "<h2>Mixed Grill/Karisik Izgara<span>",
    "<h2>Doner Kebab(Gyro)<span>",
    "<h2>Adana Combo<span>",
    "<h2>Coban Kavurma (share for 2)<span>",
    "<h2>Kunefe<span>",
    "<h2>Baklava<span>",
    "<h2>Baked Rice Pudding/Sutlac<span>",
    "<h2>Turkish Custard/Kazandibi<span>",
    "<h2>Kalburabasti<span>",
    "<h2>Kadayif<span>",
    "<h2>Ice Cream on Turkish Coffee<span>",
    "<h2>Sekerpare<span>",
    "<h2>Ice Cream Scoop<span>"
  ],
  descriptions: [
    "<p>EXPERIENCE AUTHENTIC CUISINE</p>",
    "<p>Chopped tomato, cucumber, parsley, onion, peppers, dill, tossed with lemon juice and olive oil vinegar dressing.</p>",
    "<p>Arugula, tomato, cucumber, walnut, cranberry, tossed with balsamic dressing and topped with goat cheese.</p>",
    "<p>With red cabbage, lettuce, tomato, carrot, radish, corn olive and feta cheese, tossed with lemon and olive oil dressing.</p>",
    "<p>Arugula with cucumber, cherry tomatoes, slice of parmesan cheese, onions, tossed with balsamic vinegar dressing.</p>",
    "<p>Cubes of fried eggplant, mixed with fresh tomatoes, peppers, onion and garlic.</p>",
    "<p>Mashed chickpeas blended with tahini, olive oil, lemon juice and garlic</p>",
    "<p>Well chopped tomatoes, peppers, garlic, onion, hot spices, olive oil and lemon juice</p>",
    "<p>Yogurt mixed with dry mint, butter and garlic</p>",
    "<p>Smoked eggplant mixed with bell roasted pepper, tomato, parsley garlic and olive oil</p>",
    "<p>Grape leaves stuffed with specially seasoned rice, topped with olive oil</p>",
    "<p>Mixture of green beans,tomatoes, onions, carrots, green peppers, garlic,  cooked in olive oil for perfection</p>",
    "<p>Served with seasoned onions</p>",
    "<p>Cigar-shaped pastry stuffed with cheese and parsley</p>",
    "<p>Served with marinara sauce</p>",
    "<p>Bulgur, minced onions, finely ground lean lamb, walnut, spices</p>",
    "<p>Tender pieces of char-grilled calamari, seasoned with garlic, tarragon and parsley, served with house salad</p>",
    "<p>Ball-shaped mashed chickpeas mixed with parsley and seasonings, deep fried</p>",
    "<p>Served with marinara sauce</p>",
    "<p>Spinach and cheese filled filo pastry</p>",
    "<p>Minced meat filled filo pastry</p>",
    "<p>Your choice of red or white sauce</p>",
    "<p>Grilled marinated chicken rolled up in lavash bread with humus, roasted red bell peppers, tomatoes, carrots and lettuce</p>",
    "<p>Served with lettuce, onion, tomato, carrot and hot or white sauce</p>",
    "<p>Hand chopped lamb mixed with red bell peppers, seasonings, grilled on skewer, wrapped in a lavash with tomato and lettuce</p>",
    "<p>Served with lettuce, tomato, carrot and hot or white sauce</p>",
    "<p>Grilled marinated chicken cubes, wrapped in a lavash with tomato, carrot  and lettuce</p>",
    "<p>Served with lettuce, humus, tomatoes, carrots and tahini sauce</p>",
    "<p>Fries can be substituted for additional charge</p>",
    "<p>With salmon, calamari and shrimps. Made with your choice of homemade red  or white sauce</p>",
    "<p>Light dough, stuffed with ground lamb and onion in garlic and yogurt sauce\n" +
      "  </p>",
    "<p>Served with homemade vodka marinara sauce and topped with parmesan cheese</p>",
    "<p>Baby okra baked with fresh tomatoes, onions, green peppers, served with rice</p>",
    "<p>Eight pieces of falafel served on a bed of hummus with grilled tomato, grilled pepper and house salad. Tahini sauce on the top</p>",
    "<p>A fine mixture of seasonal vegetables sauteed with our light tomato sauce, served wit rice or bulgur</p>",
    "<p>Chicken breast, red pepper, green pepper, mushroom, curry served with rice</p>",
    "<p>Marinated cubes of chicken, grilled on skewer, served with rice and house salad</p>",
    "<p>Ground chicken flavored with red bell peppers, parsley, seasoned with paprika and grilled on skewers</p>",
    "<p>Chicken breast cooked in garlic wine sauce, topped with cheese and asparagus, served with mashed potato and steam vegetables</p>",
    "<p>Served with house salad and choice of rice or bulgur</p>",
    "<p>Well seasoned and mixed with Kashari cheese, grilled\n" +
      "chicken patties, served with French fries and choice of\n" +
      "rice or bulgur</p>",
    "<p>Braised chicken over silky and delicious eggplant puree</p>",
    "<p>Grilled tender pieces of chicken legs served with house salad and rice or bulgur</p>",
    "<p>Served with house salad, your choice whole or fillet</p>",
    "<p>Grilled shrimp on skewer with peppers, tomato, onions, served with rice and house salad</p>",
    "<p>Served with mashed potato and grilled vegetables</p>",
    "<p>Served with House Salad</p>",
    "<p>Slowly simmered tender lamb shank served with mashed potato</p>",
    "<p>Grilled marinated tender lamb chops, served with rice and house salad\n" +
      "  </p>",
    "<p>Braised lamb over silky and delicious eggplant puree</p>",
    "<p>Cabbage leaves stuffed with ground lamb, rice, fresh dill and seasonings</p>",
    "<p>Hand chopped lamb mixed with red bell peppers, seasoning and grilled on skewer, served with rice and house salad</p>",
    "<p>Baby pieces of tender lamb, marinated in our special sauce and grilled to perfection, served with rice and house salad</p>",
    "<p>Well-seasoned mixture of ground lamb and beef, served with rice and french fries</p>",
    "<p>Doner kebab served over fried pide bread topped with a fresh tomato sauce, yogurt on the side</p>",
    "<p>Combination of Chicken Adana, Inegol Meatballs, Lamb Chop, Lamb Doner, Chicken Shish, served with house salad and rice</p>",
    "<p>Fresh ground lamb marinated with our own secret blend of seasoning, cooked on a rotating spit then thinly sliced</p>",
    "<p>Combination of Lamb and Chicken Adana</p>",
    "<p>In this classic Turkish dessert, delicate leaves of crisp, golden fill are layered with a tempting mixture of crushed walnuts, pistachio, sugar and clove. Laden with rich, sweet, homemade syrup, our baklava is virtually irresistible\n" +
      "  </p>",
    "<p>A delectable light pudding of broiled milk, rice and sugar, flavored with cinnamon, baked in the oven and then cooled in a clay bowl</p>",
    "<p>Upside-down pudding, traditional Turkish style milk pudding, make it from scratch. Served lightly topped with ground pistachio</p>",
    "<p>Baked soft cookies with walnuts, soaked in syrup.</p>",
    "<p>Oven baked shredded dough with walnuts filling in thick syrup.</p>",
    "<p>Delightfully combined Vanilla Ice cream and Turkish coffee, topped with whipped cream.</p>",
    "<p>Baked soft cookies soaked in syrup.</p>"
  ],
  prices: [
    "<span>$8</span>",
    "<span>$8</span>",
    "<span>Sm.$12.95 / Lg.$16.95</span>",
    "<span>$16.50</span>",
    "<span>$14.95</span>",
    "<span>$15.50</span>",
    "<span>$8.50</span>",
    "<span>$8.50</span>",
    "<span>$8.50</span>",
    "<span>$8.50</span>",
    "<span>$8.50</span>",
    "<span>$9.95</span>",
    "<span>Sm.$19.95 / Lg.$25.95</span>",
    "<span>$9.95</span>",
    "<span>$13.95</span>",
    "<span>$10.50</span>",
    "<span>$13.95</span>",
    "<span>$11</span>",
    "<span>$12.50</span>",
    "<span>$14.95</span>",
    "<span>$11.50</span>",
    "<span>$19.95</span>",
    "<span>$11.50</span>",
    "<span>$12</span>",
    "<span>$12</span>",
    "<span>$7</span>",
    "<span>$14.50</span>",
    "<span>$13.50</span>",
    "<span>$12.50</span>",
    "<span>$13.50</span>",
    "<span>$12.50</span>",
    "<span>$12.50</span>",
    "<span>$12.50</span>",
    "<span>$26.95</span>",
    "<span>$22.50</span>",
    "<span>$19.95</span>",
    "<span>$20.50</span>",
    "<span>$20.50</span>",
    "<span>$20.50</span>",
    "<span>$20.50</span>",
    "<span>$21.50</span>",
    "<span>$20.95</span>",
    "<span>$21.95</span>",
    "<span>$20.50</span>",
    "<span>$22.50</span>",
    "<span>$21.95</span>",
    "<span>$20.95</span>",
    "<span>$22.50</span>",
    "<span>$21.95</span>",
    "<span>$22.50</span>",
    "<span>$24.50</span>",
    "<span>$26.95</span>",
    "<span>$23.95</span>",
    "<span>$25.50</span>",
    "<span>$25.50</span>",
    "<span>$26.95</span>",
    "<span>$26.95</span>",
    "<span>$28.95</span>",
    "<span>$24.95</span>",
    "<span>$21.50</span>",
    "<span>$21.95</span>",
    "<span>$27.50</span>",
    "<span>$21.50</span>",
    "<span>$23.50</span>",
    "<span>$29.50</span>",
    "<span>$20.50</span>",
    "<span>$21</span>",
    "<span>$36.50</span>",
    "<span>$10.50</span>",
    "<span>$8.50</span>",
    "<span>$8</span>",
    "<span>$8</span>",
    "<span>$7.50</span>",
    "<span>$10.50</span>",
    "<span>$8.50</span>",
    "<span>$7</span>",
    "<span>$3</span>"
  ]
};
export default menu;
